#ifndef OPCODES_H
#define OPCODES_H

enum LOGIN_OPCODES {
CL_INIT = 0x01,
SV_INIT = 0x02,
CL_USERNAME_MSG = 0x03,
SV_PASS_SEED = 0x04,
CL_PASS_MSG = 0x05,
SV_USERAUTHD = 0x06,

//Character / Server listing opcodes:
CL_CHARPASS_MSG = 0x09,
SV_CHARAUTHD = 0x0A,
CL_REQSERVERLIST = 0x07,
SV_SERVERLIST = 0x08,
CL_REQCHARLIST = 0x0B,
SV_CHARLIST = 0x0C,
CL_ISZONEOK = 0x0D,
SV_ZONEOK = 0x0E,
};



#endif
